### ISSUE TITLE
Open stream behind reverse proxy

### ISSUE THREAD

**Issue by MisterTimn** [SourceLabOrg/kafka-webview#143] opened 2019-03-13 09:41 UTC
Thanks to the work on #137 we are running kafka-webview behind a reverse proxy on our K8s clusters. It has been a tremendous help to quickly debug our flows!

Only hickup we encounter now is that the stream view/websocket still redirects to the old URL (not prefixed). When checking calls we see it performing a `GET https://myhost/websocket/info?t=1550846293947` instead of a `GET https://myhost/{configured pathPrefix}/websocket/info?t=1550846293947`

**Comment by Crim** [comment] 2019-03-19 02:14
Sorry for the delayed response, I've been out on vacation.

Let me dig into this and see if I can reproduce it.  I was fairly certain I verified this use case, but it's very possible that I've missed it.

**Comment by Crim** [comment] 2019-03-19 02:22
Able to reproduce it, looks like I missed it 🤦‍♂️ Let me put together a fix.

**Comment by Crim** [comment] 2019-03-19 02:42
I committed a fix.  I may roll the changes from #150 together with this into a single upcoming release.

**Comment by Crim** [comment] 2019-03-20 07:35
Released in [2.2.0](https://github.com/SourceLabOrg/kafka-webview/releases/tag/v2.2.0).

**Closed by Crim** 2019-03-20 07:35 UTC
